import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {normalize,number,growth} from '../lib/normalize.js';import handler,{loadLive} from '../api/data.js';import {generateKeyPairSync} from 'node:crypto';
const raw=JSON.parse(await readFile(new URL('../data/snapshot.json',import.meta.url)));const d=normalize(raw);
test('Source cohort, paired quality and conversion goal reconcile',()=>{assert.equal(d.quality.length,126);const q=d.quality.filter(r=>r.a!==null&&r.b!==null);assert.equal(q.length,123);assert.equal(q.filter(r=>r.b>r.a).length,96);assert.equal(d.pit.length,30);assert.equal(d.pit.filter(r=>growth(r)>=.25).length,24);assert.equal(d.pit.reduce((s,r)=>s+r.rb-r.ra,0),234266);assert.equal(d.need.length,18);assert.equal(d.vertical.length,19)});
test('Percent text, zeros and missing baselines remain distinct',()=>{assert.equal(number('72%'),.72);assert.equal(number(''),null);assert.equal(number('NA'),null);assert.equal(number(0),0);assert.equal(growth({a:0,b:.1}),null);assert.equal(growth({a:.02,b:.025}).toFixed(2),'0.25')});
test('Source row references and duplicated CTET labels preserved',()=>{assert.deepEqual(d.need.filter(r=>r.name==='CTET LKO').map(r=>r.row),[11,14]);assert.equal(d.total.b,.7843)});
test('Column reorder rejected instead of silently corrupting metrics',()=>{const x=structuredClone(raw);[x.pit[0][18],x.pit[0][19]]=[x.pit[0][19],x.pit[0][18]];assert.throws(()=>normalize(x),/Column layout/)});
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(data){this.body=data;return this}});
test('Protected API fails closed and demo never claims live',async()=>{process.env.DASHBOARD_PASSWORD='test-password-only';process.env.DEMO_MODE='true';let r=response();await handler({method:'GET',headers:{}},r);assert.equal(r.code,401);r=response();await handler({method:'GET',headers:{authorization:'Bearer test-password-only'}},r);assert.equal(r.code,200);assert.equal(r.body.mode,'snapshot');assert.equal(r.headers['Cache-Control'],'private, no-store');assert.equal(r.body.data.pit.length,30);delete process.env.DEMO_MODE});
test('Live route resolves supplied GIDs and reads refreshed values',async()=>{const old=globalThis.fetch;const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});process.env.GOOGLE_PRIVATE_KEY=privateKey.export({format:'pem',type:'pkcs8'});process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL='test@example.invalid';const gids=[158772495,0,548945396,976295352],keys=['quality','vertical','need','pit'];let requests=0;globalThis.fetch=async(url)=>{requests++;let value;if(String(url).includes('oauth2'))value={access_token:'mock'};else if(String(url).includes('values:batchGet'))value={valueRanges:keys.map(k=>({values:raw[k]}))};else value={sheets:gids.map((sheetId,i)=>({properties:{sheetId,title:keys[i]}}))};return {ok:true,json:async()=>value}};try{const live=await loadLive();assert.equal(live.data.pit.length,30);assert.equal(requests,3);raw.pit[1][19]=.05;assert.equal((await loadLive()).data.pit[0].b,.05);raw.pit[1][19]=.032}finally{globalThis.fetch=old;delete process.env.GOOGLE_PRIVATE_KEY;delete process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL}});
