import {createSign,timingSafeEqual} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {normalize} from '../lib/normalize.js';
let tokenCache=null;
const defaults={quality:'158772495',vertical:'0',need:'548945396',pit:'976295352'};
async function request(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Google data request failed ('+r.status+'). Check Sheets API, credentials and Viewer access.');return r.json()}
async function token(){if(tokenCache&&tokenCache.exp>Date.now())return tokenCache.value;const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!email||!key)throw Error('Google Sheets connection is not configured.');const now=Math.floor(Date.now()/1000);const enc=o=>Buffer.from(JSON.stringify(o)).toString('base64url');const payload=enc({alg:'RS256',typ:'JWT'})+'.'+enc({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const signer=createSign('RSA-SHA256');signer.update(payload);const jwt=payload+'.'+signer.sign(key,'base64url');const t=await request('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});tokenCache={value:t.access_token,exp:Date.now()+3300000};return t.access_token}
export async function loadLive(){const id=process.env.GOOGLE_SHEET_ID||'1IKyZqMEZHckG0ArQQAomXluzRMwyoGfgA5LGwtoYhKU';const base='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id);const headers={Authorization:'Bearer '+await token()};const meta=await request(base+'?fields=sheets.properties',{headers});const keys=Object.keys(defaults);const titles=keys.map(k=>{const gid=process.env['GID_'+k.toUpperCase()]??defaults[k];const sheet=meta.sheets.find(s=>String(s.properties.sheetId)===String(gid));if(!sheet)throw Error('Configured GID not found for '+k);return sheet.properties.title});const query=new URLSearchParams({valueRenderOption:'UNFORMATTED_VALUE',dateTimeRenderOption:'SERIAL_NUMBER'});titles.forEach(t=>query.append('ranges',"'"+t.replaceAll("'","''")+"'!A1:AD"));const data=await request(base+'/values:batchGet?'+query,{headers});return {data:normalize(Object.fromEntries(keys.map((k,i)=>[k,data.valueRanges[i].values||[]]))),tabs:Object.fromEntries(keys.map((k,i)=>[k,titles[i]]))}}
export default async function handler(req,res){res.setHeader('Cache-Control','private, no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const password=process.env.DASHBOARD_PASSWORD;if(!password)return res.status(503).json({error:'Set DASHBOARD_PASSWORD on the server before accessing employee data.'});const given=Buffer.from((req.headers.authorization||'').replace(/^Bearer /,'')),expected=Buffer.from(password);if(given.length!==expected.length||!timingSafeEqual(given,expected))return res.status(401).json({error:'Enter the dashboard access password.'});try{if(process.env.DEMO_MODE==='true'){const raw=JSON.parse(await readFile(new URL('../data/snapshot.json',import.meta.url),'utf8'));return res.status(200).json({data:normalize(raw),mode:'snapshot',fetchedAt:new Date().toISOString(),source:'Uploaded September 2026 workbook'})}const r=await loadLive();return res.status(200).json({...r,mode:'live',fetchedAt:new Date().toISOString()})}catch(e){return res.status(503).json({error:e.message.startsWith('error:')?'Unable to authenticate with Google. Check service account configuration.':e.message})}}
